export const defaultTheme = {
  colorWhite: '#ffffff',
  colorBlack: '#333333',
  colorGrey: '#f6f6f6',
  colorLightBlue: '#d8ecfe',
  colorLightGreen: '#e1edce',
  colorGreen: '#88aa4d',
  colorLightRed: '#f8ddd7',
  colorRed: '#f75531',
  colorOrange: '#fc9b27',
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  pageWidth: "1280px",
  pagePadding: "90px",
  indent: "20px",
}
